--- 
branches: 
  include: 
    - master
displayName: |-
    Install Salesforce CLI
    - bash:
         sfdx force:auth:jwt:grant --clientid $(salesforceProdClientid) --jwtkeyfile $(server.key) --username $(salesforceProdUsername) --instanceurl $(salesforceProdInstanceUrl) -a prod
    
    
    
      displayName: Authorize salesforce org
    
    
    
    - bash:
    
    
    
        sfdx force:source:convert -d ./src
    
    
    
      displayName: Convert to deploy source
    
    
    
    - bash:
    
    
    
        sfdx force:mdapi:deploy -l RunLocalTests -c -d ./src -u prod -w 10
    
    
    
      displayName: Run validation on source code
    
    
    
    - bash:
    
    
    
        sfdx force:mdapi:deploy -d ./src -u prod -w 10
    
    
    
     displayName: Deploy source code to Production
jobs: 
  - 
    condition: "and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/master'))"
    job: ProdDeploy
    steps: 
      - 
        task: UseNode@1
      - 
        bash: "npm install sfdx-cli --global"
paths: 
  exclude: 
    - README.md
trigger: 
  autoCancel: "true"
  batch: "true"
  branches: 
    exclude: 
      - README.md
      - |-
          azure-pipelines.yml
          pr:
    include: 
      - master
    paths: ~
